name: Ubuntu environment build

on:
  push:
    branches:
      - 'main'
      - 'stable'
      - 'beta'
      - 'release/**'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_test:
    name: Build and Test Ubuntu
    runs-on: [runs-on,runner=8cpu-linux-x64,"image=ubuntu24-full-x64","run-id=${{ github.run_id }}"]
    steps:
      - id: date
        name: Set Date as Tag
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: meta
        name: Set Image Metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            px4/px4-dev
            ghcr.io/px4/px4-dev
          tags: |
            type=schedule,pattern={{date 'YYY-MM-DD'}}

      - id: build
        name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          file: ./Tools/container/Dockerfile

      - name: Test Docker Works
        run: |
          REPO_NAME=${{ steps.build.outputs.imageid }} ./Tools/container/docker_run.sh make px4_fmu-v4

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
